/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senac.sp.padoka.interfaces.cliente;

import br.senac.sp.padoka.dao.ClienteDAO;
import br.senac.sp.padoka.dao.EnderecoDAO;
import br.senac.sp.padoka.model.Cliente;
import br.senac.sp.padoka.model.Endereco;
import br.senac.sp.padoka.util.ConverteData;
import br.senac.sp.padoka.util.VerificaTelaAberta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nathan.ferreira
 */
public class TelaClientes extends javax.swing.JFrame {

    private EnderecoDAO enderecoDAO;
    private ClienteDAO clienteDAO;

    /**
     * Creates new form TelaClientes
     */
    public TelaClientes() {
        initComponents();

        enderecoDAO = new EnderecoDAO();
        clienteDAO = new ClienteDAO();

        // SETA O TÍTULO
        setTitle("Clientes");

        // FECHA SOMENTE O JFRAME ATUAL, AO INVÉS DO APP
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // SETA O FAVICON
        setIconImage(new ImageIcon(TelaClientes.class.getResource("/imagens/favicon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        btnCriar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(248, 220, 183));

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "NASCIMENTO", "CELULAR", "TELEFONE", "EMAIL", "SEXO", "ENDEREÇO", "ESTADO CIVIL", "OBSERVAÇÕES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaClientes.setMaximumSize(new java.awt.Dimension(480, 430));
        tabelaClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tabelaClientes);
        if (tabelaClientes.getColumnModel().getColumnCount() > 0) {
            tabelaClientes.getColumnModel().getColumn(0).setMinWidth(20);
            tabelaClientes.getColumnModel().getColumn(0).setMaxWidth(20);
        }

        btnCriar.setBackground(new java.awt.Color(248, 220, 183));
        btnCriar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCriar.setForeground(new java.awt.Color(94, 50, 8));
        btnCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/criarUsuario.png"))); // NOI18N
        btnCriar.setText("CRIAR");
        btnCriar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCriar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCriar.setMaximumSize(new java.awt.Dimension(95, 55));
        btnCriar.setMinimumSize(new java.awt.Dimension(95, 55));
        btnCriar.setPreferredSize(new java.awt.Dimension(95, 55));
        btnCriar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(248, 220, 183));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(94, 50, 8));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setMaximumSize(new java.awt.Dimension(95, 55));
        btnEditar.setMinimumSize(new java.awt.Dimension(95, 55));
        btnEditar.setPreferredSize(new java.awt.Dimension(95, 55));
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(248, 220, 183));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(94, 50, 8));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setMaximumSize(new java.awt.Dimension(95, 55));
        btnExcluir.setMinimumSize(new java.awt.Dimension(95, 55));
        btnExcluir.setPreferredSize(new java.awt.Dimension(95, 55));
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 691, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCriar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        new VerificaTelaAberta().verificaTelaAberta(new TelaCadastroCliente(), this, btnCriar, true);
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) tabelaClientes.getModel();
        int linhaSelecionada = tabelaClientes.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir.");
        } else {
            int confirm = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o cliente selecionado?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                clienteDAO.deletar((int) tabela.getValueAt(linhaSelecionada, 0));
                tabela.removeRow(linhaSelecionada);
            }
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        List<Cliente> listaClientes = clienteDAO.listarClientes();

        DefaultTableModel tabela = (DefaultTableModel) tabelaClientes.getModel();
        tabela.setRowCount(0);

        for (Cliente cliente : listaClientes) {
            tabela.addRow(new Object[]{
                cliente.getId(),
                cliente.getNome(),
                cliente.getCPF(),
                cliente.getData_de_nascimento(),
                cliente.getCelular(),
                cliente.getTelefone(),
                cliente.getEmail(),
                cliente.getSexo(),
                cliente.getEndereco().toString(),
                cliente.getEstado_civil(),
                cliente.getObservacoes()
            });
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        TelaCadastroCliente tela = new TelaCadastroCliente(true);
        DefaultTableModel tabela = (DefaultTableModel) tabelaClientes.getModel();

        int linhaSelecionada = tabelaClientes.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para editar.");
        } else {
            new VerificaTelaAberta().verificaTelaAberta(tela, this, btnEditar, true);
            Cliente clienteEdit = new Cliente();
            Endereco enderecoEdit = enderecoDAO.getEndereco((int) tabela.getValueAt(linhaSelecionada, 0));

            tela.txtNome.setText((String) tabela.getValueAt(linhaSelecionada, 1));
            tela.txtCPF.setText((String) tabela.getValueAt(linhaSelecionada, 2));
            tela.txtDataNascimento.setText(ConverteData.converteData((String) tabela.getValueAt(linhaSelecionada, 3), "BR"));
            tela.txtCelular.setText((String) tabela.getValueAt(linhaSelecionada, 4));
            tela.txtTelefone.setText((String) tabela.getValueAt(linhaSelecionada, 5));
            tela.txtEmail.setText((String) tabela.getValueAt(linhaSelecionada, 6));
            tela.txtSexo.setSelectedItem(tabela.getValueAt(linhaSelecionada, 7));
            tela.txtEstadoCivil.setSelectedItem(tabela.getValueAt(linhaSelecionada, 9));
            tela.txtObservacoes.setText((String) tabela.getValueAt(linhaSelecionada, 10));

            if (enderecoEdit != null) {
                tela.txtCEP.setText(enderecoEdit.getCep());
                tela.txtLogradouro.setText(enderecoEdit.getLogradouro());
                tela.txtNumero.setText(enderecoEdit.getNumero());
                tela.txtBairro.setText(enderecoEdit.getBairro());
                tela.txtComplemento.setText(enderecoEdit.getComplemento());
                tela.txtUF.setText(enderecoEdit.getUf());
                tela.txtCidade.setText(enderecoEdit.getLocalidade());
            }

            tela.btnConfirmar.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {

                    clienteEdit.setNome(tela.txtNome.getText());
                    clienteEdit.setCPF(tela.txtCPF.getText());
                    clienteEdit.setData_de_nascimento(ConverteData.converteData(tela.txtDataNascimento.getText(), "US"));
                    clienteEdit.setSexo((String) tela.txtSexo.getSelectedItem());
                    clienteEdit.setEstado_civil((String) tela.txtEstadoCivil.getSelectedItem());
                    clienteEdit.setCelular(tela.txtCelular.getText());

                    clienteEdit.setTelefone(tela.txtTelefone.getText());
                    clienteEdit.setEmail(tela.txtEmail.getText());
                    clienteEdit.setObservacoes(tela.txtObservacoes.getText());
                    clienteEdit.setId((int) tabela.getValueAt(linhaSelecionada, 0));

                    clienteDAO.atualizar(clienteEdit);

                    enderecoEdit.setCep(tela.txtCEP.getText());
                    enderecoEdit.setLogradouro(tela.txtLogradouro.getText());
                    enderecoEdit.setNumero(tela.txtNumero.getText());
                    enderecoEdit.setBairro(tela.txtBairro.getText());
                    enderecoEdit.setComplemento(tela.txtComplemento.getText());
                    enderecoEdit.setUf(tela.txtUF.getText());
                    enderecoEdit.setLocalidade(tela.txtCidade.getText());

                    enderecoDAO.atualizar(enderecoEdit);

                    JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso!");
                    tela.dispose();

                }
            });
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelaClientes;
    // End of variables declaration//GEN-END:variables
}
