/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senac.sp.padoka.interfaces.relatorios;

import br.senac.sp.padoka.dao.RelatorioAnaliticoDAO;
import br.senac.sp.padoka.dao.VendaDAO;
import br.senac.sp.padoka.interfaces.cliente.TelaCadastroCliente;
import br.senac.sp.padoka.model.Cliente;
import br.senac.sp.padoka.util.VerificaTelaAberta;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author nathan.hvferreira
 */
public class TelaRelatorioVendas extends javax.swing.JFrame {

    /**
     * Creates new form TelaRelatorioVendas
     */
    Cliente cliente = new Cliente();

    public TelaRelatorioVendas() {
        initComponents();

        // SETA O TÍTULO DO JFRAME
        setTitle("Relatório de vendas");

        // FECHA SOMENTE O JFRAME ATUAL, AO INVÉS DO APP
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // SETA O FAVICON
        setIconImage(new ImageIcon(TelaCadastroCliente.class.getResource("/imagens/favicon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        btnGerarAnalitico = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        DataFinal1 = new javax.swing.JLabel();
        DataInicial2 = new javax.swing.JLabel();
        txtDataFinal = new javax.swing.JFormattedTextField();
        txtDataInicial = new javax.swing.JFormattedTextField();
        txtIDCliente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnGerarSintetico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(248, 220, 183));
        jPanel6.setMaximumSize(new java.awt.Dimension(450, 330));
        jPanel6.setMinimumSize(new java.awt.Dimension(450, 330));

        jTabbedPane4.setBackground(new java.awt.Color(248, 220, 183));
        jTabbedPane4.setForeground(new java.awt.Color(94, 50, 8));
        jTabbedPane4.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTabbedPane4.setMaximumSize(new java.awt.Dimension(430, 250));
        jTabbedPane4.setMinimumSize(new java.awt.Dimension(430, 250));
        jTabbedPane4.setPreferredSize(new java.awt.Dimension(430, 250));

        jPanel7.setBackground(new java.awt.Color(248, 220, 183));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel7.setMaximumSize(new java.awt.Dimension(438, 283));
        jPanel7.setMinimumSize(new java.awt.Dimension(438, 283));

        btnGerarAnalitico.setBackground(new java.awt.Color(248, 220, 183));
        btnGerarAnalitico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGerarAnalitico.setForeground(new java.awt.Color(94, 50, 8));
        btnGerarAnalitico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        btnGerarAnalitico.setText("GERAR");
        btnGerarAnalitico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGerarAnalitico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGerarAnalitico.setMaximumSize(new java.awt.Dimension(95, 55));
        btnGerarAnalitico.setMinimumSize(new java.awt.Dimension(95, 55));
        btnGerarAnalitico.setPreferredSize(new java.awt.Dimension(95, 55));
        btnGerarAnalitico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGerarAnalitico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGerarAnaliticoMouseClicked(evt);
            }
        });
        btnGerarAnalitico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarAnaliticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGerarAnalitico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGerarAnalitico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("ANALÍTICO", jPanel7);

        jPanel8.setBackground(new java.awt.Color(248, 220, 183));

        DataFinal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DataFinal1.setForeground(new java.awt.Color(94, 50, 8));
        DataFinal1.setText("DATA FINAL:");
        DataFinal1.setMaximumSize(new java.awt.Dimension(42, 16));
        DataFinal1.setMinimumSize(new java.awt.Dimension(42, 16));
        DataFinal1.setPreferredSize(new java.awt.Dimension(42, 16));

        DataInicial2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DataInicial2.setForeground(new java.awt.Color(94, 50, 8));
        DataInicial2.setText("DATA INICIAL:");
        DataInicial2.setMaximumSize(new java.awt.Dimension(42, 16));
        DataInicial2.setMinimumSize(new java.awt.Dimension(42, 16));
        DataInicial2.setPreferredSize(new java.awt.Dimension(42, 16));

        try {
            txtDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataFinal.setMaximumSize(new java.awt.Dimension(100, 30));
        txtDataFinal.setMinimumSize(new java.awt.Dimension(100, 30));
        txtDataFinal.setPreferredSize(new java.awt.Dimension(100, 30));
        txtDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataFinalActionPerformed(evt);
            }
        });

        try {
            txtDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataInicial.setMaximumSize(new java.awt.Dimension(100, 30));
        txtDataInicial.setMinimumSize(new java.awt.Dimension(100, 30));
        txtDataInicial.setPreferredSize(new java.awt.Dimension(100, 30));
        txtDataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataInicialActionPerformed(evt);
            }
        });

        txtIDCliente.setMaximumSize(new java.awt.Dimension(310, 30));
        txtIDCliente.setMinimumSize(new java.awt.Dimension(310, 30));
        txtIDCliente.setPreferredSize(new java.awt.Dimension(310, 30));
        txtIDCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDClienteFocusLost(evt);
            }
        });
        txtIDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDClienteActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(94, 50, 8));
        jLabel15.setText("ID CLIENTE");

        txtNomeCliente.setEnabled(false);
        txtNomeCliente.setMaximumSize(new java.awt.Dimension(310, 30));
        txtNomeCliente.setMinimumSize(new java.awt.Dimension(310, 30));
        txtNomeCliente.setPreferredSize(new java.awt.Dimension(310, 30));
        txtNomeCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeClienteFocusLost(evt);
            }
        });
        txtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(94, 50, 8));
        jLabel16.setText("NOME CLIENTE");

        btnGerarSintetico.setBackground(new java.awt.Color(248, 220, 183));
        btnGerarSintetico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGerarSintetico.setForeground(new java.awt.Color(94, 50, 8));
        btnGerarSintetico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        btnGerarSintetico.setText("GERAR");
        btnGerarSintetico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGerarSintetico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGerarSintetico.setMaximumSize(new java.awt.Dimension(95, 55));
        btnGerarSintetico.setMinimumSize(new java.awt.Dimension(95, 55));
        btnGerarSintetico.setPreferredSize(new java.awt.Dimension(95, 55));
        btnGerarSintetico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGerarSintetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarSinteticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addComponent(DataFinal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addComponent(DataInicial2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnGerarSintetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataInicial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103)
                .addComponent(btnGerarSintetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane4.addTab("SINTÉTICO", jPanel8);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarAnaliticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarAnaliticoActionPerformed
        new VerificaTelaAberta().verificaTelaAberta(new TelaRelatorioAnalitico(), this, btnGerarAnalitico, true);
    }//GEN-LAST:event_btnGerarAnaliticoActionPerformed

    private void btnGerarAnaliticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerarAnaliticoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerarAnaliticoMouseClicked

    private void txtDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFinalActionPerformed

    private void txtDataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicialActionPerformed

    private void txtIDClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDClienteFocusLost
        VendaDAO venda = new VendaDAO();

        cliente = venda.buscaCliente(Integer.parseInt(txtIDCliente.getText()));

        txtNomeCliente.setText(cliente.getNome());
    }//GEN-LAST:event_txtIDClienteFocusLost

    private void txtIDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDClienteActionPerformed

    private void txtNomeClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeClienteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteFocusLost

    private void txtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteActionPerformed

    private void btnGerarSinteticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarSinteticoActionPerformed
        if (txtIDCliente.getText().isEmpty() || txtDataInicial.getText().isEmpty() || txtDataFinal.getText().isEmpty()) {
            btnGerarSintetico.disable();
            JOptionPane.showMessageDialog(rootPane, "Preencha o ID do cliente e/ou data inicial e/ou data final e/ou selecione o tipo de relatório");
        } else {
            new VerificaTelaAberta().verificaTelaAberta(new TelaRelatorioSintetico(), this, btnGerarSintetico, true);
        }
    }//GEN-LAST:event_btnGerarSinteticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorioVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataFinal1;
    private javax.swing.JLabel DataInicial2;
    public javax.swing.JButton btnGerarAnalitico;
    private javax.swing.JButton btnGerarSintetico;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane4;
    public javax.swing.JFormattedTextField txtDataFinal;
    public javax.swing.JFormattedTextField txtDataInicial;
    private javax.swing.JTextField txtIDCliente;
    private javax.swing.JTextField txtNomeCliente;
    // End of variables declaration//GEN-END:variables
}
